### ISSUE TITLE
Unknown function: win_getid

### ISSUE THREAD

**Issue by silenc3r** [cloudhead/neovim-fuzzy#1]
I get following error when trying to use this plugin:
```
Error detected while processing function <SNR>17_fuzzy:
line   47:
E117: Unknown function: win_getid
E15: Invalid expression: win_getid()
```
Neovim version: 0.1.4
Terminal: Gnome Terminal
$TERM: xterm-256color
system: Fedora 23

**Comment by KillTheMule** [comment]
Upgrade your neovim, the `win_getid´ function was ported for 0.1.5, see https://github.com/neovim/neovim/pull/5117.

**Comment by silenc3r** [comment]
It'd be good to specify minimal neovim version in dependencies.

**Comment by cloudhead** [comment]
Yep, fixed (https://github.com/cloudhead/neovim-fuzzy/commit/5cb4c8219925e87b24b34e3e3a3aaafaf1a6cce3).
