### ISSUE TITLE
Is it possible to enable finding "hidden" files?

### ISSUE THREAD

**Issue by gfairchild** [cloudhead/neovim-fuzzy#12]
When I bring up the finder, how can I enable finding "hidden" files? For example, if I have a file named `.config`, it currently doesn't appear in my search results if I search for "config". Is there a way to enable this?

**Comment by cloudhead** [comment]
I think I'm going to enable this by default, as it seems to still respect .gitignore and doesn't search in .git directories.

**Comment by gfairchild** [comment]
Sounds good to me. I like respecting `.gitignore` and ignoring `.git` directories.

**Comment by cloudhead** [comment]
Here we go: https://github.com/cloudhead/neovim-fuzzy/commit/b9242e3c33223e2556e5ab4e71daeb77c945af74

Try it out and let me know.

**Comment by gfairchild** [comment]
Just updated. Looks like it is including the stuff in `.git` but is ignoring files specified in `.gitignore`.

![screen shot 2016-10-26 at 11 20 24 am](https://cloud.githubusercontent.com/assets/2835900/19736828/3aaf3d78-9b6e-11e6-9259-d1449edfe610.png)

![screen shot 2016-10-26 at 11 20 32 am](https://cloud.githubusercontent.com/assets/2835900/19736831/3c5a82e0-9b6e-11e6-8b22-2b25462c6ecb.png)

**Comment by cloudhead** [comment]
Ah yes, it's because I have a `.ignore` file in my home directory with `.git/` in it. You can do that for now, but I'm going to probably turn this into an option instead of default.

**Comment by gfairchild** [comment]
Having that as an option seems smart. I have dozens of git projects, and it would be nice to have a global option to turn it off for all projects.

**Comment by gfairchild** [comment]
And actually, now that I think about it, it may actually be nice to have several options:

* Ignore `.git`. This is useful for people that care about including `.git` in their search results.
* Use `.gitignore`. I have several projects where I use `.gitignore` to ignore files containing secrets (keys, passwords, etc.). I don't want these files tracked in git, but it is definitely useful to occasionally open them in vim.
* Show hidden files. Some people may not want to see hidden files, while others might.

Having fine-tuned control over each of these options would be nice.

**Comment by cloudhead** [comment]
I think what I'll do is expose a `fuzzy#open` function that can be called with a few options, then you can either use the default FuzzyOpen, or create a new command and pass whatever options you want to the open function.

**Comment by cloudhead** [comment]
I'm reverting the change for now and will look into this soon.

**Comment by gfairchild** [comment]
Sounds reasonable. Thanks!

**Comment by 1ak31sha** [comment]
i would like the option to find hidden/dotfiles. is it available?

**Comment by cloudhead** [comment]
Fixed in #49
