### ISSUE TITLE
Error when run FuzzyOpen in neovim

### ISSUE THREAD

**Issue by HiddenPython** [cloudhead/neovim-fuzzy#14]
**Error when run FuzzyOpen in neovim:**
Error detected while processing function <SNR>36_fuzzy_open:                                                                                                                                                
line   22:                                                                                                                                                                                                  
Vim(let):E118: Too many arguments for function: 263 

**Env:**
OS: Ubuntu 16.04.1 LTS
NVIM: 0.2.0-dev

**Comment by cloudhead** [comment]
I merged something related to this recently: https://github.com/cloudhead/neovim-fuzzy/pull/13

Can you check with latest master?

**Comment by HiddenPython** [comment]
My copy has already been the latest one.

commit 8832151646d08d69c3cf330ebb8f365764e62245
Author: Alexis Sellier <alexis@cloudhead.io>

    Merge pull request #13 from hlidotbe/master
    
    Neovim expects 3 arguments to job handlers

**Comment by leidav** [comment]
I have the same issue on arch linux with nvim 0.1.7

**Comment by adham90** [comment]
:+1:

**Comment by leidav** [comment]
I forgot to install ripgrep. It works now.

**Comment by HiddenPython** [comment]
Installing rg also solved my problem. Thanks for your information, David. But two things:
1. the error msg is not very informative
2. FuzzyOpen doesn't depend on rg or ag unlike FuzzyGrep, so it's weird that they have caused it to fail.

Do they make sense?

**Comment by cloudhead** [comment]
Error message fixed in https://github.com/cloudhead/neovim-fuzzy/commit/e3a5170d46eca972ec8449bebd8618438f3ec9eb thanks for reporting.

FuzzyOpen does depend on rg/ag, since it uses them to find files as well as search the contents of them.
