### ISSUE TITLE
Open files in splits

### ISSUE THREAD

**Issue by bronzehedwick** [cloudhead/neovim-fuzzy#15]
Is it possible to use `FuzzyOpen` to open files in a split or a tab?

Thanks!

**Comment by cloudhead** [comment]
The only way to do this at the moment is via `let g:fuzzy_opencmd = 'edit'`

Replace 'edit' with whatever command you want, like 'split'. This is a global setting though.

**Comment by bronzehedwick** [comment]
Ahh I see. I was hoping for something like [FZF](https://github.com/junegunn/fzf#usage-as-vim-plugin) or ctrl-p has, where you can type `C-X` `C-V` or `C-T` to open in a split, vsplit, or tab.

**Comment by cloudhead** [comment]
That shouldn't be too difficult, will look into it.

**Comment by bronzehedwick** [comment]
Great, thanks!

**Comment by DimiDumo** [comment]
Is this issue still active? Would be really great to have this

**Comment by willianmk** [comment]
I was checking the basic vim commands for new tab, you can also change the parameter `let g:fuzzy_opencmd` as 'tabedit' or simply 'tabe'

**Comment by cloudhead** [comment]
Fixed in #39
