### ISSUE TITLE
Getting E5060 with neovim0.2

### ISSUE THREAD

**Issue by lamarpavel** [cloudhead/neovim-fuzzy#28]
Since the update to neovim v0.2, using ag for file listing in neovim-fuzzy produces a `Vim(call):E5060: unknown flag 'w'`.

See:
https://github.com/neovim/neovim/pull/6427/files#diff-deb695d507653839019814f54242d47bR17430

The culprit lies here:
https://github.com/cloudhead/neovim-fuzzy/blob/master/plugin/neovim-fuzzy.vim#L73

Changing this line to `call writefile(a:ignorelist, ignorefile, 's')` fixes the issue.

**Comment by cloudhead** [comment]
Fixed in 5f7afa98b8f109c0c62dcfc824f0debf1e5d7212, please confirm it works.

**Comment by lamarpavel** [comment]
Just tested with `NVIM v0.2.0` and can confirm it works. Thanks.
