### ISSUE TITLE
fuzzy_open Unknown flag w

### ISSUE THREAD

**Issue by bedwards** [cloudhead/neovim-fuzzy#29]
Disclaimer: I am completely new to all of this.

Ubuntu 17.04, ag 1.0.2, fzy 0.9, nvim v0.2.1-dev

FuzzyGrep works

FuzzyOpen prints out

```
Error detected while processing function <SNR>9_fuzzy_open:
line 24:
Vim(call):E5060: Unknow flag: w
```

my best guess is writefile call

**Comment by cloudhead** [comment]
Same error as https://github.com/cloudhead/neovim-fuzzy/issues/28
Will fix.

**Comment by bedwards** [comment]
Yes, works now. Thanks.
