### ISSUE TITLE
:FuzzyOpen searches in root directory

### ISSUE THREAD

**Issue by spf3000** [cloudhead/neovim-fuzzy#36]
Hi I installed this on Ubuntu and it works great - on my mac though - whenever I use :FuzzyOpen it starts the search from the root directory - rather than my current directory. It's possible it's something in my setup but I can't think what - my init.vim is the same for both machines.

**Comment by cloudhead** [comment]
By default, it will look for the closest .git directory to start from. Could that be it? If you create a git or hg repo then it will use that as the root.

**Comment by spf3000** [comment]
Err, yes that was it. Somehow I had put my root as a git directory! I feel silly but also very relieved. Thanks!
