### ISSUE TITLE
Strip colors

### ISSUE THREAD

**Issue by balta2ar** [cloudhead/neovim-fuzzy#4]
Someone's leaving colors in the output, and it looks as if nvim can't open the file because of that:
![](https://i.imgur.com/GiSkm3w.png)

I tried adding `--nocolor` to https://github.com/cloudhead/neovim-fuzzy/blob/master/plugin/neovim-fuzzy.vim#L12, but it didn't help...

**Comment by balta2ar** [comment]
> adding --nocolor [...] didn't help.

It turned out it wasn't true. I'm using dein, so I had to do this after I hacked your plugin's source:
``` vim
:call dein#recache_runtimepath()
```
So in fact, `--nocolor` helped. Though I still think stripping out colors is a good idea.

**Comment by cloudhead** [comment]
Yikes. Not sure why I haven't run into this, but I fixed it here: https://github.com/cloudhead/neovim-fuzzy/commit/1ef2ffede8f874b83f7f09a89bd8a0cf5cd488e1

Cheers

**Comment by balta2ar** [comment]
Thanks!
