### ISSUE TITLE
press ctrlP error:Fuzzy: no search executable was found. Please make sure either 'ag' or 'rg' are in your path

### ISSUE THREAD

**Issue by JackXuXin** [cloudhead/neovim-fuzzy#44]
![image](https://user-images.githubusercontent.com/24310518/58687783-33081e00-83b5-11e9-94d4-c90ba3761ee4.png)

**Comment by cloudhead** [comment]
Check the README, it states that either `rg` (ripgrep) or `ag` are requirements.
