### ISSUE TITLE
How to open a file in a few tab?

### ISSUE THREAD

**Issue by gfairchild** [cloudhead/neovim-fuzzy#7]
How can I open a file in a new tab instead of replacing the currently open file tab?

**Comment by cloudhead** [comment]
You can change the default behaviour by setting `g:fuzzy_opencmd`, but there's currently no way to do it on a per-file basis.

.vimrc:
```
let g:fuzzy_opencmd = 'tabedit'
```

**Comment by gfairchild** [comment]
Perfect! Thanks!
