### ISSUE TITLE
Unknown function win_getid?

### ISSUE THREAD

**Issue by jedahan** [cloudhead/neovim-fuzzy#8]
when trying to run `:FuzzyOpen`, on OSX(OSX El Capitan, iTerm2 3.0.9, zsh 5.2, fzy 0.7, neovim 0.1.4), and centos(centos 7.0.1406, iTerm2 3.0.9, zsh 5.0.8, fzy 0.7, neovim 0.1.4):

```
Error detected while processing function <SNR>104_fuzzy_open[36]..<SNR>104_fuzzy:
line   42:
E117: Unknown function: win_getid
E15: Invalid expression: win_getid()
Press ENTER or type command to continue
```

**Comment by cloudhead** [comment]
Upgrade your neovim :)

**Comment by jedahan** [comment]
Upgraded to 0.1.5, removed ag and sift and it works great now :D
