### ISSUE TITLE
Wrong argument when invoking

### ISSUE THREAD

**Issue by digitalcosmos** [cloudhead/neovim-fuzzy#9]
I get an error message saying `--path-to-ignore` is not a valid argument.
Changing to `--path-to-agignore` seems to fix the issue.

I'm running ag version 0.31.0.

**Comment by cloudhead** [comment]
`ag` and `ripgrep (rg)` have standardized on the `.ignore` file name and thus ag renamed its option to `--path-to-ignore` recently. I suggest updating to the latest, and I will update the requirements in the readme.
